### PR TITLE
FF support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by InputNeuron** [comment]
Nice.. a lot of good work here.

Did you setup the webpack support via something like 'create-react-app' or just did it by hand?

I'm trying to wrap my head around all this functionality (typescript + webpack) as I need to do the same for the polar website for publicly sharing this data.

**Comment by InputNeuron** [comment]
Also,  REALLY like the chrome extension uploader... I'll work on verifying this stuff soon and try to merge.

**Comment by andytnt** [comment]
@burtonator Did you check it?

**Comment by InputNeuron** [comment]
Still going to work on merging this. Just been slammed on getting the next release done and haven't been working on the extension.

The plan is to rework the extension here soon and have the extension installed first which then downloads the desktop client

**Pull request closed without merging**
